sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build --no-cache -t woodygoodjob/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true woodygoodjob/react-test npm test

after_success:
  - docker build -t woodygoodjob/multi-client ./client
  - docker build -t woodygoodjob/multi-nginx ./nginx
  - docker build -t woodygoodjob/multi-server ./server
  - docker build -t woodygoodjob/multi-worker ./worker
  # log in the docker CLI
  - echo "$docker_password" | docker login -u "$docker_id" --password-stdin
  # push the built images to dockerhub 
  - docker push woodygoodjob/multi-client
  - docker push woodygoodjob/multi-nginx
  - docker push woodygoodjob/multi-server
  - docker push woodygoodjob/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-west-2-255107891704'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY 