sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t woodygoodjob/react-test -f ./client/Dockerfile.dev .



script:
  - docker run -e CI=true woodygoodjob/react-test npm test

after_success:
  - docker build -t woodygoodjob/multi-client ./client
  - docker build -t woodygoodjob/multi-nginx ./nginx
  - docker build -t woodygoodjob/multi-server ./server
  - docker build -t woodygoodjob/multi-worker ./worker
  # log in the docker CLI
  - echo "$docker_password" | docker login -u "$docker_id" --password-stdin
  # push the built images to dockerhub 
  - docker push woodygoodjob/multi-client
  - docker push woodygoodjob/multi-nginx
  - docker push woodygoodjob/multi-services
  - docker push woodygoodjob/multi-worker